version: "3.8"
services:
  joberty_service:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:-jobertyBackendRuntime}
    container_name: joberty
    restart: on-failure
    ports:
      - 8088:8080
    environment:
      JOBERTY_SERVICE_PORT: ${JOBERTY_SERVICE_PORT}
      JOBERTY_DB_URL: ${JOBERTY_DB_URL}
      JOBERTY_DB_USER: ${JOBERTY_DB_USER}
      JOBERTY_DB_PASS: ${JOBERTY_DB_PASS}
    depends_on: 
      - joberty_db
    
  joberty_db:
    image: postgres:14.1
    container_name: joberty_db
    restart: always
    environment:
       POSTGRES_USER: ${JOBERTY_DB_USER}
       POSTGRES_PASSWORD: ${JOBERTY_DB_PASS}
       POSTGRES_DB: ${JOBERTY_DB_NAME}
       POSTGRES_HOST: ${JOBERTY_DB_HOST}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: maraipera5@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped     
